all:
	clang++ -std=c++14 -I../include recurse.cpp -o recurse
	clang++ -std=c++14 -I../include at.cpp -o at
	clang++ -std=c++14 -I../include lu.cpp -o lu
	clang++ -std=c++14 -I../include strings.cpp -o strings
	clang++ -std=c++14 -I../include map.cpp -o map
